### ISSUE TITLE
Creating estimated cost field(s)?

### ISSUE THREAD

**Issue by infracritical** [certsocietegenerale/FIR#125] opened 2016-09-08 18:34 UTC
Need fields for actual monetary figures, perhaps a range of low and high values of the estimated cost incurred for the occurrence.

**Comment by gaelmuller** [comment] 2016-09-09 07:42
Seems to be a duplicate of https://github.com/certsocietegenerale/FIR/issues/123

**Closed by gaelmuller** 2016-09-09 07:42 UTC
Labels: duplicate
