### ISSUE TITLE
Bad Request using docker image (compose method)

### ISSUE THREAD

**Issue by riskynacho** [certsocietegenerale/FIR#268] opened 2021-10-27 07:30 UTC
Just tried the docker files you shared in the docker directory, when it comes up, I try to access it via ip address and a hostname I gave it, it returns - Bad Request (400).

**Comment by rafaeldrs** [comment] 2022-01-28 18:59
Same here. I just did some digging and found that "fir" image (the one that is built from the Dockerfile) has some errors. After the container with the fir image fails, fir_web container fails too, and so it's inaccessible.

**Comment by Augustin-FL** [comment] 2022-02-10 13:40
Hi there,

I'm assuming that's due to the Django version. some `import` and functions have been deprecated on the current version. this cause the fir image to fail at runtime

I made a pull request for fixing this : https://github.com/certsocietegenerale/FIR/pull/272

**Comment by certsocietegenerale** [comment] 2022-02-11 12:32
Hello,

Sorry for the delay. The PR has been merged, could you confirm the issue is fixed now?

**Comment by rafaeldrs** [comment] 2022-02-17 20:34
> Hello,
> 
> Sorry for the delay. The PR has been merged, could you confirm the issue is fixed now?

Yes, it is solved now. Thanks!

**Closed** 2022-02-18 08:52 UTC
