### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by vmsv** [certsocietegenerale/FIR#244] opened 2018-12-08 16:08 UTC
I have made the production installation according to the instructions. I can see my admin user in the database, and I'm sure the pwd is correct. However I can't logging into the admin portal.

I'm using the latest github version. My reverse proxy is being done by apache and not nginx.

Every time I try to logon I get a password/ username wrong, which doesn't make sense.

**Comment by satyaakam** [comment] 2019-02-07 15:58
try running ./manage.py createsuperuser --settings fir.config.production

**Comment by certsocietegenerale** [comment] 2022-08-24 13:42
Hello,

It is probably caused by permission issues.

Please try to login to the admin panel directly : `http://<yourFIRDomain>/admin/`
As suggested above please use `./manage.py` to create a new user/reset a password if you can't login to the admin panel.

From the admin panel, you should be able to manage groups, permissions & ACLs. Please make sure your users have at least one role on one business line, and are part of the "Incident Viewer" group

We will close this issue since it is very old.
Feel free to re-open it if needed

**Closed by certsocietegenerale** 2022-08-24 13:42 UTC
