### ISSUE TITLE
502 BadGateway Error

### ISSUE THREAD

**Issue by mahesh557** [certsocietegenerale/FIR#188] opened 2017-03-08 05:22 UTC
Hi,
I am following instructions on https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment.
I am getting 502 Bad Gateway Error when attempted to http://localhost/admin

I am using ubuntu 16.04 LTS 64 bit

```
(env-FIR) uma@uma-virtual-machine:~/FIR/FIR/fir/config$ head production.py
..
ALLOWED_HOSTS = ['FIR.DOMAIN.COM','127.0.0.1','localhost']


(env-FIR) uma@uma-virtual-machine:~/FIR/FIR/fir/config$ cat /etc/systemd/system/fir_uwsgi.service 
[Unit]
Description=uWSGI instance for FIR
After=syslog.target

[Service]
User=nginx
Group=nginx
WorkingDirectory=/home/uma/FIR/FIR/
ExecStart=/usr/bin/uwsgi --socket /home/uma/FIR/FIR/run/fir.sock --chdir /home/uma/FIR/FIR/ --module fir.wsgi
Restart=always
KillSignal=SIGQUIT
Type=Debug
StandardError=syslog
NotifyAccess=All

[Install]

● fir_uwsgi.service - uWSGI instance for FIR
   Loaded: loaded (/etc/systemd/system/fir_uwsgi.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Mar 08 00:20:53 uma-virtual-machine systemd[1]: fir_uwsgi.service: Unit entered failed state.
Mar 08 00:20:53 uma-virtual-machine systemd[1]: fir_uwsgi.service: Failed with result 'exit-code'.
Mar 08 00:20:54 uma-virtual-machine systemd[1]: fir_uwsgi.service: Service hold-off time over, scheduling restart.
Mar 08 00:20:54 uma-virtual-machine systemd[1]: Stopped uWSGI instance for FIR.
Mar 08 00:20:54 uma-virtual-machine systemd[1]: fir_uwsgi.service: Start request repeated too quickly.
Mar 08 00:20:54 uma-virtual-machine systemd[1]: Failed to start uWSGI instance for FIR.
Mar 08 00:21:21 uma-virtual-machine systemd[1]: [/etc/systemd/system/fir_uwsgi.service:12] Failed to parse service type, ignoring: Debug
Mar 08 00:21:21 uma-virtual-machine systemd[1]: [/etc/systemd/system/fir_uwsgi.service:14] Failed to parse notify access specifier, ignoring: All
Mar 08 00:22:07 uma-virtual-machine systemd[1]: [/etc/systemd/system/fir_uwsgi.service:12] Failed to parse service type, ignoring: Debug
Mar 08 00:22:07 uma-virtual-machine systemd[1]: [/etc/systemd/system/fir_uwsgi.service:14] Failed to parse notify access specifier, ignoring: All

```

**Comment by mahesh557** [comment] 2017-03-08 05:40
Found i don't have /usr/bin/uwsgi
However found at another path /usr/local/bin/uwsgi
Replaced the same in /etc/systemd/system/fir_uwsgi.service
and restarted the service.
Yet the Problem Persists. uWSGI not instantiated !!!

'''
uma@uma-virtual-machine:~/FIR/FIR$ sudo service fir_uwsgi status
● fir_uwsgi.service - uWSGI instance for FIR
   Loaded: loaded (/etc/systemd/system/fir_uwsgi.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Mar 08 00:35:54 uma-virtual-machine systemd[1]: Started uWSGI instance for FIR.
Mar 08 00:35:54 uma-virtual-machine systemd[1]: fir_uwsgi.service: Main process exited, code=exited, status=217/USER
Mar 08 00:35:54 uma-virtual-machine systemd[1]: fir_uwsgi.service: Unit entered failed state.
Mar 08 00:35:54 uma-virtual-machine systemd[1]: fir_uwsgi.service: Failed with result 'exit-code'.
Mar 08 00:35:54 uma-virtual-machine systemd[1]: fir_uwsgi.service: Service hold-off time over, scheduling restart.
Mar 08 00:35:54 uma-virtual-machine systemd[1]: Stopped uWSGI instance for FIR.
Mar 08 00:35:54 uma-virtual-machine systemd[1]: fir_uwsgi.service: Start request repeated too quickly.
Mar 08 00:35:54 uma-virtual-machine systemd[1]: Failed to start uWSGI instance for FIR.
Mar 08 00:35:56 uma-virtual-machine systemd[1]: [/etc/systemd/system/fir_uwsgi.service:12] Failed to parse service type, ignoring: Debug
Mar 08 00:35:56 uma-virtual-machine systemd[1]: [/etc/systemd/system/fir_uwsgi.service:14] Failed to parse notify access specifier, ignoring: All
uma@uma-virtual-machine:~/FIR/FIR$ cat /etc/systemd/system/fir_uwsgi.service
[Unit]
Description=uWSGI instance for FIR
After=syslog.target

[Service]
User=nginx
Group=nginx
WorkingDirectory=/home/uma/FIR/FIR/
ExecStart=/usr/local/bin/uwsgi --socket /home/uma/FIR/FIR/run/fir.sock --chdir /home/uma/FIR/FIR/ --module fir.wsgi
Restart=always
KillSignal=SIGQUIT
Type=Debug
StandardError=syslog
NotifyAccess=All

[Install]
WantedBy=multi-user.targetuma@uma-virtual-machine:~/FIR/FIR$ /usr/local/bin/uwsgi --socket /home/uma/FIR/FIR/run/fir.sock --chdir /home/uma/FIR/FIR/ --module fir.wsgi
*** Starting uWSGI 2.0.14 (64bit) on [Wed Mar  8 00:36:37 2017] ***
compiled with version: 5.4.0 20160609 on 07 March 2017 22:50:06
os: Linux-4.8.0-39-generic #42~16.04.1-Ubuntu SMP Mon Feb 20 15:06:07 UTC 2017
nodename: uma-virtual-machine
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/uma/FIR/FIR
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/uma/FIR/FIR/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 8070
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/uma/FIR/FIR/run/fir.sock fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1327940
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1327940 pid: 8807 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 8807, cores: 1)

'''

**Comment by gaelmuller** [comment] 2017-03-21 12:40
Sorry about the delay, are you still having this issue ?

If so, could you provide your nginx configuration as well as your nginx error logs ?

**Comment by RANGERBEE** [comment] 2017-05-03 21:18
Im getting same issue...  Tried even changing permissions on folder to open it up and still no joy.

![image](https://cloud.githubusercontent.com/assets/15255470/25682011/0c6acd8e-3046-11e7-9900-56b2524d3eef.png)

**Comment by RANGERBEE** [comment] 2017-05-04 14:05
I think this is the issue / fix. I just dont know how to go about it...

http://stackoverflow.com/questions/41038159/cant-run-uwsgi-ini-file-with-systemd-emperor

**Comment by Mackousko12** [comment] 2017-09-22 15:44
Try replacing the following:-

/usr/bin/uwsgi --socket /home/uma/FIR/FIR/run/fir.sock --chdir /home/uma/FIR/FIR/ --plugins python --module fir.wsgi

**Comment by cruxofit** [comment] 2017-10-12 19:39
Check to see if you actually have the user "nginx".... cat /etc/passwd

If not change the User / Group to a valid user in this file: /etc/systemd/system/fir_uwsgi.service

**Comment by Augustin-FL** [comment] 2023-08-22 10:54
The problem is related to your systemd config. You have
```
User=nginx
Group=nginx
```
in your config, but your fame instance is in `/home/uma/FIR`.


You need to either change the username used by systemd when launching fir...or alternatively, you need to change the location of FIR files. They should be in a location readable by nginx user (eg, `/usr/share/nginx/html/`, `/var/www/html`, etc..)

This issue is 6 years old, your problem likely got already resolved in the meantime. I will close it, feel free to re-open it if needed.

**Closed by Augustin-FL** 2023-08-22 10:54 UTC
