### ISSUE TITLE
#tab_open only show loading

### ISSUE THREAD

**Issue by ian119** [certsocietegenerale/FIR#59] opened 2016-01-26 06:50 UTC
I got the tab  show Loading.... only.

**Comment by tomchop** [comment] 2016-01-26 09:43
Could you be a little more specific please? What setup are you using? What browser (version, etc.) are you using? Do you have any extensions running such as NoScript?

**Comment by kylekoza** [comment] 2016-01-26 12:46
I ran into this on my last install. The fix was to go into the admin panel and add a profile for my user account. (Site Administration -> Incidents -> Profiles -> Add)

**Comment by ian119** [comment] 2016-01-27 02:51
Thanks Kyle Koza,

I got your solutions. Thanks.

On 26 January 2016 at 20:46, Kyle Koza <notifications@github.com> wrote:

> I ran into this on my last install. The fix was to go into the admin panel
> and add a profile for my user account. (Site Administration -> Incidents ->
> Profiles -> Add)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/certsocietegenerale/FIR/issues/59#issuecomment-174996705>
> .
>



-- 
Sofian Akasah
Phone : 01121964945

**Comment by gaelmuller** [comment] 2016-02-15 16:11
I'm closing this since:

* I cannot reproduce this issue (profile is automatically created if it doesn't exists).
* The fact that you should create a profile is mentioned in the documentation.

**Closed by gaelmuller** 2016-02-15 16:11 UTC
